/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.validation;

import uk.ac.kcl.inf.cw.edu.validation.AbstractEduLangauageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EduLangauageValidator extends AbstractEduLangauageValidator {
}
