/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.cw.edu.ui.internal.EduActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EduLangauageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EduActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EduActivator activator = EduActivator.getInstance();
		return activator != null ? activator.getInjector(EduActivator.UK_AC_KCL_INF_CW_EDU_EDULANGAUAGE) : null;
	}

}
