/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.ide;

import uk.ac.kcl.inf.cw.edu.ide.AbstractEduLangauageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EduLangauageIdeModule extends AbstractEduLangauageIdeModule {
}
