/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.cw.edu.EduLangauageRuntimeModule;
import uk.ac.kcl.inf.cw.edu.EduLangauageStandaloneSetup;
import uk.ac.kcl.inf.cw.edu.ide.EduLangauageIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EduLangauageIdeSetup extends EduLangauageStandaloneSetup {
  @Override
  public Injector createInjector() {
    EduLangauageRuntimeModule _eduLangauageRuntimeModule = new EduLangauageRuntimeModule();
    EduLangauageIdeModule _eduLangauageIdeModule = new EduLangauageIdeModule();
    return Guice.createInjector(Modules2.mixin(_eduLangauageRuntimeModule, _eduLangauageIdeModule));
  }
}
