/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEduLangauageScopeProvider extends DelegatingScopeProvider {
}
