/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.ui.contentassist;

import uk.ac.kcl.inf.cw.edu.ui.contentassist.AbstractEduLangauageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EduLangauageProposalProvider extends AbstractEduLangauageProposalProvider {
}
