/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.eduLangauage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Addition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getLeft <em>Left</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getAddition()
 * @model
 * @generated
 */
public interface Addition extends IntExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(IntExpression)
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getAddition_Left()
   * @model containment="true"
   * @generated
   */
  IntExpression getLeft();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(IntExpression value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.cw.edu.eduLangauage.IntExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference list.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getAddition_Right()
   * @model containment="true"
   * @generated
   */
  EList<IntExpression> getRight();

} // Addition
