/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.eduLangauage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauageFactory
 * @model kind="package"
 * @generated
 */
public interface EduLangauagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "eduLangauage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/cw/edu/EduLangauage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "eduLangauage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  EduLangauagePackage eINSTANCE = uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoProgramImpl <em>Trigo Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoProgramImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getTrigoProgram()
   * @generated
   */
  int TRIGO_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGO_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Trigo Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGO_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.StatementImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.SideStatementImpl <em>Side Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.SideStatementImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getSideStatement()
   * @generated
   */
  int SIDE_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDE_STATEMENT__COMMAND = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDE_STATEMENT__STEPS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Side Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIDE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoStatementImpl <em>Trigo Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoStatementImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getTrigoStatement()
   * @generated
   */
  int TRIGO_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGO_STATEMENT__COMMAND = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGO_STATEMENT__STEPS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Trigo Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGO_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntExpressionImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 5;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntLiteralImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableReferenceImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getVariableReference()
   * @generated
   */
  int VARIABLE_REFERENCE = 7;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE__VAR = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.AdditionImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.MultiplicationImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.DivisionImpl <em>Division</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.DivisionImpl
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getDivision()
   * @generated
   */
  int DIVISION = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Division</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVISION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand <em>Side Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getSideCommand()
   * @generated
   */
  int SIDE_COMMAND = 11;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand <em>Angle Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getAngleCommand()
   * @generated
   */
  int ANGLE_COMMAND = 12;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoProgram <em>Trigo Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigo Program</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoProgram
   * @generated
   */
  EClass getTrigoProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoProgram#getStatements()
   * @see #getTrigoProgram()
   * @generated
   */
  EReference getTrigoProgram_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EReference getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement <em>Side Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Side Statement</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement
   * @generated
   */
  EClass getSideStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getCommand()
   * @see #getSideStatement()
   * @generated
   */
  EAttribute getSideStatement_Command();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Steps</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getSteps()
   * @see #getSideStatement()
   * @generated
   */
  EAttribute getSideStatement_Steps();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement <em>Trigo Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigo Statement</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement
   * @generated
   */
  EClass getTrigoStatement();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getCommand()
   * @see #getTrigoStatement()
   * @generated
   */
  EAttribute getTrigoStatement_Command();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Steps</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getSteps()
   * @see #getTrigoStatement()
   * @generated
   */
  EReference getTrigoStatement_Steps();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.VariableReference <em>Variable Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Reference</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.VariableReference
   * @generated
   */
  EClass getVariableReference();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.VariableReference#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.VariableReference#getVar()
   * @see #getVariableReference()
   * @generated
   */
  EReference getVariableReference_Var();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Division <em>Division</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Division</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Division
   * @generated
   */
  EClass getDivision();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Division#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Division#getLeft()
   * @see #getDivision()
   * @generated
   */
  EReference getDivision_Left();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.Division#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.Division#getRight()
   * @see #getDivision()
   * @generated
   */
  EReference getDivision_Right();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand <em>Side Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Side Command</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand
   * @generated
   */
  EEnum getSideCommand();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand <em>Angle Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Angle Command</em>'.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand
   * @generated
   */
  EEnum getAngleCommand();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  EduLangauageFactory getEduLangauageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoProgramImpl <em>Trigo Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoProgramImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getTrigoProgram()
     * @generated
     */
    EClass TRIGO_PROGRAM = eINSTANCE.getTrigoProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGO_PROGRAM__STATEMENTS = eINSTANCE.getTrigoProgram_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.StatementImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.SideStatementImpl <em>Side Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.SideStatementImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getSideStatement()
     * @generated
     */
    EClass SIDE_STATEMENT = eINSTANCE.getSideStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIDE_STATEMENT__COMMAND = eINSTANCE.getSideStatement_Command();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIDE_STATEMENT__STEPS = eINSTANCE.getSideStatement_Steps();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoStatementImpl <em>Trigo Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.TrigoStatementImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getTrigoStatement()
     * @generated
     */
    EClass TRIGO_STATEMENT = eINSTANCE.getTrigoStatement();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGO_STATEMENT__COMMAND = eINSTANCE.getTrigoStatement_Command();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGO_STATEMENT__STEPS = eINSTANCE.getTrigoStatement_Steps();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntExpressionImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.IntLiteralImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.VariableReferenceImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getVariableReference()
     * @generated
     */
    EClass VARIABLE_REFERENCE = eINSTANCE.getVariableReference();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_REFERENCE__VAR = eINSTANCE.getVariableReference_Var();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.AdditionImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.MultiplicationImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.impl.DivisionImpl <em>Division</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.DivisionImpl
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getDivision()
     * @generated
     */
    EClass DIVISION = eINSTANCE.getDivision();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVISION__LEFT = eINSTANCE.getDivision_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVISION__RIGHT = eINSTANCE.getDivision_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand <em>Side Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getSideCommand()
     * @generated
     */
    EEnum SIDE_COMMAND = eINSTANCE.getSideCommand();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand <em>Angle Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand
     * @see uk.ac.kcl.inf.cw.edu.eduLangauage.impl.EduLangauagePackageImpl#getAngleCommand()
     * @generated
     */
    EEnum ANGLE_COMMAND = eINSTANCE.getAngleCommand();

  }

} //EduLangauagePackage
