/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.eduLangauage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getIntExpression()
 * @model
 * @generated
 */
public interface IntExpression extends EObject
{
} // IntExpression
