/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.eduLangauage;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Side Command</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getSideCommand()
 * @model
 * @generated
 */
public enum SideCommand implements Enumerator
{
  /**
   * The '<em><b>Adjacent</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ADJACENT_VALUE
   * @generated
   * @ordered
   */
  ADJACENT(0, "adjacent", "adjacent"),

  /**
   * The '<em><b>Opposite</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OPPOSITE_VALUE
   * @generated
   * @ordered
   */
  OPPOSITE(1, "opposite", "opposite"),

  /**
   * The '<em><b>Hypotenuse</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HYPOTENUSE_VALUE
   * @generated
   * @ordered
   */
  HYPOTENUSE(2, "hypotenuse", "hypotenuse");

  /**
   * The '<em><b>Adjacent</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ADJACENT
   * @model name="adjacent"
   * @generated
   * @ordered
   */
  public static final int ADJACENT_VALUE = 0;

  /**
   * The '<em><b>Opposite</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OPPOSITE
   * @model name="opposite"
   * @generated
   * @ordered
   */
  public static final int OPPOSITE_VALUE = 1;

  /**
   * The '<em><b>Hypotenuse</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HYPOTENUSE
   * @model name="hypotenuse"
   * @generated
   * @ordered
   */
  public static final int HYPOTENUSE_VALUE = 2;

  /**
   * An array of all the '<em><b>Side Command</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final SideCommand[] VALUES_ARRAY =
    new SideCommand[]
    {
      ADJACENT,
      OPPOSITE,
      HYPOTENUSE,
    };

  /**
   * A public read-only list of all the '<em><b>Side Command</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<SideCommand> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Side Command</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SideCommand get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SideCommand result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Side Command</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SideCommand getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      SideCommand result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Side Command</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static SideCommand get(int value)
  {
    switch (value)
    {
      case ADJACENT_VALUE: return ADJACENT;
      case OPPOSITE_VALUE: return OPPOSITE;
      case HYPOTENUSE_VALUE: return HYPOTENUSE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private SideCommand(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //SideCommand
