/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.eduLangauage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Side Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getCommand <em>Command</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getSideStatement()
 * @model
 * @generated
 */
public interface SideStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand
   * @see #setCommand(SideCommand)
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getSideStatement_Command()
   * @model
   * @generated
   */
  SideCommand getCommand();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.SideCommand
   * @see #getCommand()
   * @generated
   */
  void setCommand(SideCommand value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' attribute.
   * @see #setSteps(float)
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getSideStatement_Steps()
   * @model
   * @generated
   */
  float getSteps();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.SideStatement#getSteps <em>Steps</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Steps</em>' attribute.
   * @see #getSteps()
   * @generated
   */
  void setSteps(float value);

} // SideStatement
