/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.eduLangauage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trigo Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getCommand <em>Command</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getTrigoStatement()
 * @model
 * @generated
 */
public interface TrigoStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand
   * @see #setCommand(AngleCommand)
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getTrigoStatement_Command()
   * @model
   * @generated
   */
  AngleCommand getCommand();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.AngleCommand
   * @see #getCommand()
   * @generated
   */
  void setCommand(AngleCommand value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference.
   * @see #setSteps(IntExpression)
   * @see uk.ac.kcl.inf.cw.edu.eduLangauage.EduLangauagePackage#getTrigoStatement_Steps()
   * @model containment="true"
   * @generated
   */
  IntExpression getSteps();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cw.edu.eduLangauage.TrigoStatement#getSteps <em>Steps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Steps</em>' containment reference.
   * @see #getSteps()
   * @generated
   */
  void setSteps(IntExpression value);

} // TrigoStatement
