/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.cw.edu.parser.antlr.internal.InternalEduLangauageParser;
import uk.ac.kcl.inf.cw.edu.services.EduLangauageGrammarAccess;

public class EduLangauageParser extends AbstractAntlrParser {

	@Inject
	private EduLangauageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEduLangauageParser createParser(XtextTokenStream stream) {
		return new InternalEduLangauageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TrigoProgram";
	}

	public EduLangauageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EduLangauageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
