/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu;

import uk.ac.kcl.inf.cw.edu.AbstractEduLangauageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EduLangauageRuntimeModule extends AbstractEduLangauageRuntimeModule {
}
