/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu;

import uk.ac.kcl.inf.cw.edu.EduLangauageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EduLangauageStandaloneSetup extends EduLangauageStandaloneSetupGenerated {
  public static void doSetup() {
    new EduLangauageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
