/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class EduLangauageUiModule extends AbstractEduLangauageUiModule {
}
