/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cw.edu.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.cw.edu.ui.internal.EduActivator;

public class EduLangauageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EduActivator.getInstance().getInjector("uk.ac.kcl.inf.cw.edu.EduLangauage");
	}

}
